import type { NextConfig } from "next";

const slugMap: Record<string, Record<string, string>> = {
  fr: {
    dtv: 'visa-dtv-thailande',
    'elite-visa': 'visa-elite-thailande',
    'tourist-visa': 'visa-touristique-thailande',
    'retirement-visa': 'visa-retraite-thailande',
    services: 'services-et-tarifs',
    contact: 'nous-contacter',
    faq: 'questions-frequentes',
    terms: 'conditions-generales',
    sitemap: 'plan-du-site',
    search: 'comparateur-visa-thailande-2026',
    ltr: 'visa-ltr-thailande',
    'visa-run': 'risques-visa-run-thailande',
    'business-visa': 'visa-business-thailande',
    'exemption-visa': 'exemption-visa-thailande',
    'student-visa': 'visa-etudiant-thailande',
    'family-visa': 'visa-famille-thailande',
    'smart-visa': 'smart-visa-thailande',
    'volunteer-visa': 'visa-volontaire-thailande',
    'medical-visa': 'visa-medical-thailande',
    'religious-visa': 'visa-religieux-thailande',
    'media-visa': 'visa-media-thailande',
    'official-visa': 'visa-officiel-thailande',
    'scientific-visa': 'visa-scientifique-thailande',
    apply: 'demande-de-visa',
    about: 'a-propos'
  },
  en: {
    dtv: 'thailand-dtv-visa',
    'elite-visa': 'thailand-elite-visa',
    'tourist-visa': 'thailand-tourist-visa',
    'retirement-visa': 'thailand-retirement-visa',
    services: 'services-and-rates',
    contact: 'contact-us',
    faq: 'frequently-asked-questions',
    terms: 'terms-and-conditions',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply-visa',
    about: 'about-us'
  },
  de: {
    dtv: 'destination-thailand-visum',
    'elite-visa': 'thailand-elite-visum',
    'tourist-visa': 'touristenvisum',
    'retirement-visa': 'ruhestandsvisum',
    services: 'leistungen',
    contact: 'kontakt',
    faq: 'haufig-gestellte-fragen',
    terms: 'allgemeine-geschaftsbedingungen',
    sitemap: 'seitenverzeichnis',
    search: 'thailand-visum-vergleich-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risiken',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply-visa',
    about: 'ueber-uns'
  },
  es: {
    dtv: 'visado-destino-tailandia',
    'elite-visa': 'visado-elite-tailandia',
    'tourist-visa': 'visado-turista',
    'retirement-visa': 'visado-jubilacion',
    services: 'servicios',
    contact: 'contacto',
    faq: 'preguntas-frecuentes',
    terms: 'terminos-y-condiciones',
    sitemap: 'mapa-del-sito',
    search: 'comparador-visas-tailandia-2026',
    ltr: 'visado-residencia-larga-duracion',
    'visa-run': 'riesgos-visa-run-tailandia',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'solicitar-visa',
    about: 'sobre-nosotros'
  },
  it: {
    dtv: 'visto-destinazione-thailandia',
    'elite-visa': 'visto-elite-thailandia',
    'tourist-visa': 'visto-turistico',
    'retirement-visa': 'visto-pensionati',
    services: 'servizi',
    contact: 'contatto',
    faq: 'domande-frequenti',
    terms: 'termini-e-condizioni',
    sitemap: 'mappa-del-sito',
    search: 'comparatore-visti-thailandia-2026',
    ltr: 'visto-residenza-lungo-termine',
    'visa-run': 'rischi-visa-run-thailandia',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'richiedi-visto',
    about: 'chi-siamo'
  },
  th: {
    dtv: 'destination-thailand-visa',
    'elite-visa': 'thailand-resident-visa',
    'tourist-visa': 'tourist-visa',
    'retirement-visa': 'retirement-visa',
    services: 'services',
    contact: 'contact',
    faq: 'faq',
    terms: 'terms',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply',
    about: 'about'
  },
  ru: {
    dtv: 'destination-thailand-visa',
    'elite-visa': 'thailand-resident-visa',
    'tourist-visa': 'tourist-visa',
    'retirement-visa': 'retirement-visa',
    services: 'services',
    contact: 'contact',
    faq: 'faq',
    terms: 'terms',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply',
    about: 'about'
  },
  zh: {
    dtv: 'destination-thailand-visa',
    'elite-visa': 'thailand-resident-visa',
    'tourist-visa': 'tourist-visa',
    'retirement-visa': 'retirement-visa',
    services: 'services',
    contact: 'contact',
    faq: 'faq',
    terms: 'terms',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'global-wealthy-citizen-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply',
    about: 'about'
  },
  ja: {
    dtv: 'destination-thailand-visa',
    'elite-visa': 'thailand-resident-visa',
    'tourist-visa': 'tourist-visa',
    'retirement-visa': 'retirement-visa',
    services: 'services',
    contact: 'contact',
    faq: 'faq',
    terms: 'terms',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply',
    about: 'about'
  },
  ko: {
    dtv: 'destination-thailand-visa',
    'elite-visa': 'thailand-resident-visa',
    'tourist-visa': 'tourist-visa',
    'retirement-visa': 'retirement-visa',
    services: 'services',
    contact: 'contact',
    faq: 'faq',
    terms: 'terms',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply',
    about: 'about'
  },
  ar: {
    dtv: 'destination-thailand-visa',
    'elite-visa': 'thailand-resident-visa',
    'tourist-visa': 'tourist-visa',
    'retirement-visa': 'retirement-visa',
    services: 'services',
    contact: 'contact',
    faq: 'faq',
    terms: 'terms',
    sitemap: 'sitemap',
    search: 'thailand-visa-comparator-2026',
    ltr: 'long-term-resident-visa',
    'visa-run': 'thailand-visa-run-risks',
    'business-visa': 'thailand-business-visa',
    'exemption-visa': 'thailand-visa-exemption',
    'student-visa': 'thailand-student-visa',
    'family-visa': 'thailand-family-visa',
    'smart-visa': 'thailand-smart-visa',
    'volunteer-visa': 'thailand-volunteer-visa',
    'medical-visa': 'thailand-medical-visa',
    'religious-visa': 'thailand-religious-visa',
    'media-visa': 'thailand-media-visa',
    'official-visa': 'thailand-official-visa',
    'scientific-visa': 'thailand-scientific-visa',
    apply: 'apply',
    about: 'about'
  }
};

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'img.antiquiscore.com',
      },
    ],
  },
  async rewrites() {
    const rewrites: any[] = [];
    Object.entries(slugMap).forEach(([lang, slugs]) => {
      Object.entries(slugs).forEach(([internal, translated]) => {
        if (internal === translated) return;
        rewrites.push({
          source: `/${lang}/${translated}`,
          destination: `/${lang}/${internal}`,
        });
      });
    });
    return rewrites;
  },
  async redirects() {
    const redirects: any[] = [];
    Object.entries(slugMap).forEach(([lang, slugs]) => {
      Object.entries(slugs).forEach(([internal, translated]) => {
        if (internal === translated) return;
        redirects.push({
          source: `/${lang}/${internal}`,
          destination: `/${lang}/${translated}`,
          permanent: true,
        });
      });
    });
    return redirects;
  },
};

export default nextConfig;
